### ISSUE TITLE
AttributeError: 'google.protobuf.pyext._message.ScalarMapContainer' object has no attribute 'extend'

### ISSUE THREAD

**Issue by dizcology** [googleapis/gapic-generator-python#672]
GAPIC package generated with [this proto](https://github.com/googleapis/googleapis/blob/master/google/cloud/aiplatform/v1beta1/endpoint_service.proto#L253) has failing unit test with the following error:

```
AttributeError: 'google.protobuf.pyext._message.ScalarMapContainer' object has no attribute 'extend'
```

**Comment by software-dov** [comment]
Can you add a section of which unit test is failing? I'm fairly certain that this bug is fixed by https://github.com/googleapis/gapic-generator-python/pull/660, but I want to be sure.

**Comment by software-dov** [comment]
Is the bug still present when using the most recent generator version?

**Comment by software-dov** [comment]
This should be fixed by #660 and can be reopened if the issue persists.
