### ISSUE TITLE
mypy test fails with gapic-generator-python 0.65.2

### ISSUE THREAD

**Issue by parthea** [googleapis/gapic-generator-python#1288]
The following code is failing the mypy test in https://github.com/googleapis/python-datastore/pull/306
```
        metadata = tuple(metadata) + (
            gapic_v1.routing_header.to_grpc_metadata((("project_id", ""),)),
        )
```

The error is
```
nox > mypy google/ tests/
tests/unit/gapic/datastore_admin_v1/test_datastore_admin.py:1817: error: Incompatible types in assignment (expression has type "Tuple[Any, ...]", variable has type "Tuple[]")
```

See build log [here](https://source.cloud.google.com/results/invocations/058d64d3-4209-4b8d-bfe6-a3fdad279c39/log).

@atulep Please could you take a look?

**Comment by vam-google** [comment]
@parthea Can you please revisit your https://github.com/googleapis/gapic-generator-python/pull/1314 PR and merge it if possible? This issue isnow showing as out of SLO for us. Thanks!

**Comment by parthea** [comment]
Closing as obsolete.
